//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week2Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int ProjectId { get; set; }
        public Nullable<int> Spreadsheets { get; set; }
        public Nullable<int> WorkOrders { get; set; }
        public Nullable<int> Presentations { get; set; }
        public bool Completed { get; set; }
        public bool Active { get; set; }
    }
}
