//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolRegistrationApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedule()
        {
            this.Professors = new HashSet<Professor>();
            this.Students = new HashSet<Student>();
        }
    
        public int ScheduleId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> ProfessorId { get; set; }
        public Nullable<int> Course1Id { get; set; }
        public Nullable<System.TimeSpan> Course1Time { get; set; }
        public Nullable<int> Course2Id { get; set; }
        public Nullable<System.TimeSpan> Course2Time { get; set; }
        public Nullable<int> Course3Id { get; set; }
        public Nullable<System.TimeSpan> Course3Time { get; set; }
        public Nullable<int> Course4Id { get; set; }
        public Nullable<System.TimeSpan> Course4Time { get; set; }
        public Nullable<int> Course5Id { get; set; }
        public Nullable<System.TimeSpan> Course5Time { get; set; }
        public Nullable<int> Course6Id { get; set; }
        public Nullable<System.TimeSpan> Course6Time { get; set; }
        public Nullable<int> Course7Id { get; set; }
        public Nullable<System.TimeSpan> Course7Time { get; set; }
        public bool Active { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Cours Cours1 { get; set; }
        public virtual Cours Cours2 { get; set; }
        public virtual Cours Cours3 { get; set; }
        public virtual Cours Cours4 { get; set; }
        public virtual Cours Cours5 { get; set; }
        public virtual Cours Cours6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Professor> Professors { get; set; }
        public virtual Professor Professor { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
    }
}
